
modLoader="kotlinforforge"
loaderVersion="${loader_version_range}"
license='${mod_license}'

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="Thanks to thedarkcolour and all the contributors for making Kotlin for Forge"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.jabm]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.jabm]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
